_BASE_: ../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 133
    TRAIN_CLASS_JSON: "datasets/coconut.json"
    TEST_CLASS_JSON: "datasets/coconut.json"
DATASETS:
  TRAIN: ("coconutL_sem_seg_train",)
  TEST: ("coconutL_sem_seg_val",)
SOLVER:
  ACCUM_STEPS: 4
  IMS_PER_BATCH: 1
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 40000
  WARMUP_ITERS: 4000
TEST:
  EVAL_PERIOD: 10000 #100000 #5000
  LOSS_EVAL_PERIOD: 5000 #1000
  MAX_IMAGES: 750 # 500
  IMS_PER_BATCH: 1 #2
#OLD_RESUME: True
