- mv
- pc59
- nyu
- idd
- a133 # DONE# DONE sh run_lora.sh configs/mv/mv.yaml 1 output/mv/ MODEL.LORA.NAME mv
- coconutL # DONEsh run_lora.sh configs/coconutL/coconutL.yaml 1 output/coconutL/ MODEL.LORA.NAME coconutL | last IoU 61.5806
- acdc-rain
- acdc-fog
- acdc-snow
- acdc-night
- muses-clear-day
- muses-clear-night
- muses-rain-day
- muses-rain-night
- muses-fog-day
- muses-fog-night
- muses-snow-night
- muses-snow-day
- cs-normal
- bdd
