_BASE_: ../base.yaml
SOLVER:
  IMS_PER_BATCH: 1 #4
  ACCUM_STEPS: 4
  MAX_ITER: 30000
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 133
    TRAIN_CLASS_JSON: "datasets/ade133.json"
    TEST_CLASS_JSON: "datasets/ade133.json"
DATASETS:
  TRAIN: ("a133_sem_seg_train",)
  TEST: ("a133_sem_seg_val",)
TEST:
  EVAL_PERIOD: 5000 #100000 #5000
  LOSS_EVAL_PERIOD: 3000 #1000
  IMS_PER_BATCH: 1 #2
INPUT:
  MIN_SIZE_TEST: 0
  MAX_SIZE_TRAIN: 700
  MAX_SIZE_TEST: 700