_BASE_: ../base.yaml
DOMAIN_NAME: pc59
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 59
    TRAIN_CLASS_JSON: "datasets/pc59.json"
    TEST_CLASS_JSON: "datasets/pc59.json"
DATASETS:
  TRAIN: ("pc59_sem_seg_train",)
  TEST: ("pc59_sem_seg_val",)
TEST:
  EVAL_PERIOD: 2000 #100000 #5000
  LOSS_EVAL_PERIOD: 500 #1000
  MAX_IMAGES: 1000 # 500
  IMS_PER_BATCH: 1 #2
SOLVER:
  IMS_PER_BATCH: 1
  ACCUM_STEPS: 4
  BASE_LR: 0.0001
  MAX_ITER: 14000
  WARMUP_ITERS: 4000